### PR TITLE
fix(restore): mark CVRs after restore is completed

### LINKED ISSUE #127: After a restore, cStorVolume remains in Init, CVRs remain in Error state
**What steps did you take and what happened:**

I wanted to test a full restore of a namespace (a single application). I tested this on a namespace called "vikunja", which contains two Deployments, two Services, two Pods, one Ingress and one PVC, backed by a cStorVolume and three cStorVolumeReplicas that are all healthy. The restore succeeded, however, in the new namespace the application never came up because its cStorVolume remains in `Init` state and its three cStorVolumeReplicas remain in `Error` state.

This is the Restore command I ran:

```
velero restore create vikunja-test-restore --from-backup volumes-full-20201011-043725 --include-namespaces 'vikunja' --namespace-mappings 'vikunja:vikunja-restore' --restore-volumes=true
```

Where `volumes-full` is a ([non-Schedule](https://github.com/openebs/velero-plugin/issues/119)) backup that contains a full copy of most of the volumes in my cluster.

The restore finished successfully in approximately one minute. Indeed, after this, the `vikunja-restore` namespace contains two Deployments, two Services, two Pods, one Ingress and one PVC. I modified the Ingress so that the endpoint URI is different from the original namespace, and visited the application at the new URI expecting to find the same application, but in the state from the backup instead of the most recent state. However, the application does not load, because the PVC cannot be mounted as the iSCSI target is not ready.

```
$ kubectl get cstorvolume -n openebs | grep 9e222
pvc-9e222d37-984f-45ad-a42b-5fac7892b51f   Init      7m48s   50Gi
$ kubectl describe cstorvolume -n openebs pvc-9e222d37-984f-45ad-a42b-5fac7892b51f 
[...]
Events:
  Type    Reason   Age    From                                                             Message
  ----    ------   ----   ----                                                             -------
  Normal  Updated  6m32s  pvc-9e222d37-984f-45ad-a42b-5fac7892b51f-target-5cf9bbd767288st  Updated resize conditions
  Normal  Updated  6m32s  pvc-9e222d37-984f-45ad-a42b-5fac7892b51f-target-5cf9bbd767288st  successfully resized volume from 0 to 50Gi
$ kubectl get cvr -n openebs | grep 9e222
pvc-9e222d37-984f-45ad-a42b-5fac7892b51f-cstor-disk-pool-eiq0   32.6M   1.76M       Error     7m55s
pvc-9e222d37-984f-45ad-a42b-5fac7892b51f-cstor-disk-pool-una0   32.6M   1.76M       Error     7m55s
pvc-9e222d37-984f-45ad-a42b-5fac7892b51f-cstor-disk-pool-7it6   32.6M   1.75M       Error     7m55s
$ kubectl describe cvr -n openebs pvc-9e222d37-984f-45ad-a42b-5fac7892b51f-cstor-disk-pool-eiq0
[...]
Events:
  Type     Reason      Age                    From                Message
  ----     ------      ----                   ----                -------
  Normal   Synced      8m55s                  CStorVolumeReplica  Received Resource create event
  Normal   Created     8m51s                  CStorVolumeReplica  Resource created successfully
  Normal   Synced      8m51s (x2 over 8m55s)  CStorVolumeReplica  Received Resource modify event
  Warning  SyncFailed  26s (x18 over 8m51s)   CStorVolumeReplica  failed to sync CVR error: unable to update snapshot list details in CVR: failed to get the list of snapshots: Output: failed listsnap command for cstor-67623196-d6e5-4956-9eb4-db81259c9089/pvc-9e222d37-984f-45ad-a42b-5fac7892b51f with err 2
```

I tried to let the situation resolve overnight but to no avail.

**What did you expect to happen:**

I expected the volume and its replicas to eventually become Healthy with the same contents as the volume had during the restored backup.

**The output of the following commands will help us better understand what's going on**:

* maya-apiserver logs (restore is around 21:24):
```
I1011 06:18:29.198928       7 backup_endpoint_v1alpha1.go:501] Deleting backup snapshot volumes-full-20201011-043725 for volume "pvc-1c329d55-f024-4306-8489-0efbd65f58c5"
I1011 06:18:29.531233       7 backup_endpoint_v1alpha1.go:507] Snapshot:'volumes-full-20201011-043725' deleted successfully for volume:pvc-1c329d55-f024-4306-8489-0efbd65f58c5
I1011 21:24:35.125935       7 volume_endpoint_v1alpha1.go:78] received cas volume request: http method {GET}
I1011 21:24:35.126216       7 volume_endpoint_v1alpha1.go:171] received volume read request: pvc-9e222d37-984f-45ad-a42b-5fac7892b51f
W1011 21:24:35.557971       7 task.go:433] notfound error at runtask {readlistsvc}: error {target service not found}
W1011 21:24:35.560904       7 runner.go:166] nothing to rollback: no rollback tasks were found
2020/10/11 21:24:35.561160 [ERR] http: Request GET /latest/volumes/pvc-9e222d37-984f-45ad-a42b-5fac7892b51f
failed to read volume: volume {pvc-9e222d37-984f-45ad-a42b-5fac7892b51f} not found in namespace {vikunja-restore}
I1011 21:24:35.574866       7 volume_endpoint_v1alpha1.go:78] received cas volume request: http method {POST}
I1011 21:24:35.575543       7 volume_endpoint_v1alpha1.go:135] received volume create request
I1011 21:24:38.119247       7 select.go:154] Overprovisioning restriction policy not added as overprovisioning is enabled on spc cstor-disk-pool
I1011 21:24:39.041828       7 volume_endpoint_v1alpha1.go:165] volume 'pvc-9e222d37-984f-45ad-a42b-5fac7892b51f' created successfully
I1011 21:24:39.058360       7 volume_endpoint_v1alpha1.go:78] received cas volume request: http method {GET}
I1011 21:24:39.058460       7 volume_endpoint_v1alpha1.go:171] received volume read request: pvc-9e222d37-984f-45ad-a42b-5fac7892b51f
I1011 21:24:42.053882       7 volume_endpoint_v1alpha1.go:226] volume 'pvc-9e222d37-984f-45ad-a42b-5fac7892b51f' read successfully
I1011 21:24:47.994475       7 restore_endpoint_v1alpha1.go:105] Restore volume 'pvc-9e222d37-984f-45ad-a42b-5fac7892b51f' created successfully 
I1011 21:24:48.937246       7 restore_endpoint_v1alpha1.go:143] Restore:volumes-full-20201011-043725-61650654-92c8-4fa3-ad5d-326c3f5a553c created for volume "pvc-9e222d37-984f-45ad-a42b-5fac7892b51f" poolUUID:223b4546-5ed3-4e1e-b8b7-7f42c4502dbb
I1011 21:24:49.503239       7 restore_endpoint_v1alpha1.go:143] Restore:volumes-full-20201011-043725-0359f610-7763-428c-b0fc-a92c2f5463c6 created for volume "pvc-9e222d37-984f-45ad-a42b-5fac7892b51f" poolUUID:30381e2c-0392-4b82-b552-ca843fdaf6d7
I1011 21:24:50.294236       7 restore_endpoint_v1alpha1.go:143] Restore:volumes-full-20201011-043725-44813e28-d02f-454e-8891-dd2b65d31a66 created for volume "pvc-9e222d37-984f-45ad-a42b-5fac7892b51f" poolUUID:67623196-d6e5-4956-9eb4-db81259c9089
I1011 21:24:55.476539       7 restore_endpoint_v1alpha1.go:246] Restore:volumes-full-20201011-043725-61650654-92c8-4fa3-ad5d-326c3f5a553c status is InProgress
I1011 21:25:00.685293       7 restore_endpoint_v1alpha1.go:246] Restore:volumes-full-20201011-043725-61650654-92c8-4fa3-ad5d-326c3f5a553c status is InProgress
I1011 21:25:06.459184       7 restore_endpoint_v1alpha1.go:246] Restore:volumes-full-20201011-043725-44813e28-d02f-454e-8891-dd2b65d31a66 status is InProgress
I1011 21:25:12.062433       7 restore_endpoint_v1alpha1.go:246] Restore:volumes-full-20201011-043725-0359f610-7763-428c-b0fc-a92c2f5463c6 status is InProgress
I1011 21:25:17.099452       7 restore_endpoint_v1alpha1.go:246] Restore:volumes-full-20201011-043725-61650654-92c8-4fa3-ad5d-326c3f5a553c status is Done
I1011 21:25:17.099542       7 restore_endpoint_v1alpha1.go:246] Restore:volumes-full-20201011-043725-44813e28-d02f-454e-8891-dd2b65d31a66 status is Done
I1011 21:25:17.099581       7 restore_endpoint_v1alpha1.go:246] Restore:volumes-full-20201011-043725-0359f610-7763-428c-b0fc-a92c2f5463c6 status is Done
I1012 04:38:52.017035       7 backup_endpoint_v1alpha1.go:160] Creating backup snapshot volumes-full-20201012-043837 for volume "pvc-318b2f41-40db-4ee7-8564-4c8677665bbf"
I1012 04:38:53.195149       7 backup_endpoint_v1alpha1.go:167] Backup snapshot:'volumes-full-20201012-043837' created successfully for volume:pvc-318b2f41-40db-4ee7-8564-4c8677665bbf
```

* `velero restore logs vikunja-test-restore | grep -v 'Skipping namespace'`: https://pastebin.com/vh9ACfAn
* `velero restore describe vikunja-test-restore`:

```
velero restore describe vikunja-test-restore
Name:         vikunja-test-restore
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  Completed

Started:    2020-10-11 23:24:29 +0200 CEST
Completed:  2020-10-11 23:25:28 +0200 CEST

Warnings:
  Velero:     <none>
  Cluster:  could not restore, persistentvolumes "pvc-9e222d37-984f-45ad-a42b-5fac7892b51f" already exists. Warning: the in-cluster version is different than the backed-up version.
  Namespaces:
    vikunja-restore:  could not restore, persistentvolumeclaims "storage" already exists. Warning: the in-cluster version is different than the backed-up version.

Backup:  volumes-full-20201011-043725

Namespaces:
  Included:  vikunja
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  vikunja=vikunja-restore

Label selector:  <none>

Restore PVs:  true
```

* Logs of the cStor disk pool pod:

```
$ kubectl logs cstor-disk-pool-7it6-657f7f5897-2tg4b -n openebs cstor-pool | grep -C3 10-11/21:24 
2020-10-11/06:17:47.588 [tgt 10.43.208.76:6060:17]: Destroy snapshot command for cstor-30381e2c-0392-4b82-b552-ca843fdaf6d7/pvc-2ef2eddc-c59f-4222-a112-6fb7ebfccdb3@volumes-full-20201011-043725
2020-10-11/06:17:50.336 [tgt 10.43.42.69:6060:16]: Create snapshot command for cstor-30381e2c-0392-4b82-b552-ca843fdaf6d7/pvc-1c329d55-f024-4306-8489-0efbd65f58c5@volumes-full-20201011-043725
2020-10-11/06:18:29.476 [tgt 10.43.42.69:6060:16]: Destroy snapshot command for cstor-30381e2c-0392-4b82-b552-ca843fdaf6d7/pvc-1c329d55-f024-4306-8489-0efbd65f58c5@volumes-full-20201011-043725
2020-10-11/21:24:42.125 zvol cstor-30381e2c-0392-4b82-b552-ca843fdaf6d7/pvc-9e222d37-984f-45ad-a42b-5fac7892b51f status change: DEGRADED -> DEGRADED
2020-10-11/21:24:42.125 zvol cstor-30381e2c-0392-4b82-b552-ca843fdaf6d7/pvc-9e222d37-984f-45ad-a42b-5fac7892b51f rebuild status change: INIT -> INIT
2020-10-11/21:24:42.126 ERROR target IP address is empty for cstor-30381e2c-0392-4b82-b552-ca843fdaf6d7/pvc-9e222d37-984f-45ad-a42b-5fac7892b51f
2020-10-12/04:38:52.176 [tgt 10.43.120.72:6060:28]: Create snapshot command for cstor-30381e2c-0392-4b82-b552-ca843fdaf6d7/pvc-318b2f41-40db-4ee7-8564-4c8677665bbf@volumes-full-20201012-043837
2020-10-12/04:41:13.316 [tgt 10.43.120.72:6060:28]: Destroy snapshot command for cstor-30381e2c-0392-4b82-b552-ca843fdaf6d7/pvc-318b2f41-40db-4ee7-8564-4c8677665bbf@volumes-full-20201012-043837
2020-10-12/04:41:17.452 [tgt 10.43.80.233:6060:18]: Create snapshot command for cstor-30381e2c-0392-4b82-b552-ca843fdaf6d7/pvc-20bffc04-703d-44b0-8820-e124a9c0bc51@volumes-full-20201012-043837
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- Velero version (use `velero version`): v1.5.1
- Velero features (use `velero client config get features`): <NOT SET>
- Velero-plugin version: openebs/velero-plugin-arm64:2.1.0
- OpenEBS version: 2.1.0
- Kubernetes version (use `kubectl version`): client 1.19.2, server 1.18.3
- Kubernetes installer & version: k3os
- Cloud provider or hardware configuration: arm64
- OS (e.g. from `/etc/os-release`): k3os

### PR DESCRIPTION
**Pull request by zlymeda**
Marking CVRs after successful restore with openebs.io/restore-completed if autoSetTargetIP=true or restoreAllIncrementalSnapshots=true

## Pull Request template

**Why is this PR required? What issue does it fix?**:
Currently users have to set targetip on CVRs after restore. This PR automates setting targetip.

**What this PR does?**:
If corresponding VolumeSnapshotLocation has autoSetTargetIP=true or restoreAllIncrementalSnapshots=true then CVRs are marked with annotation openebs.io/restore-completed which is then handled in https://github.com/openebs/maya/pull/1761 or https://github.com/openebs/cstor-operators/pull/198

**Does this PR require any upgrade changes?**:
No

**If the changes in this PR are manually verified, list down the scenarios covered and commands you used for testing with logs:**
I ran `make test`

**Any additional information for your reviewer?**:
_Mention if this PR is part of any design or a continuation of previous PRs_

related maya PR: https://github.com/openebs/maya/pull/1761
related cstor-operators PR: https://github.com/openebs/cstor-operators/pull/198

**Checklist:**
- [x] Fixes #127
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated?
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

### CODE REVIEW

File: pkg/cstor/cstor.go [hunk 1]
```diff
@@ -268,6 +274,11 @@ func (p *Plugin) Init(config map[string]string) error {
 
 	if restoreAllSnapshots, ok := config[RestoreAllIncrementalSnapshots]; ok && restoreAllSnapshots == "true" {
 		p.restoreAllSnapshots = true
+		p.autoSetTargetIP = true
+	}
+
+	if autoSetTargetIP, ok := config[AutoSetTargetIP]; ok {
```
Comment (mynktl) [inline pkg/cstor/cstor.go:280]: Here we are checking if value is set or not. We also need to check if `autoSetTargetIP` is set to "true".

File: pkg/cstor/cvr_operation.go [hunk 2]
```diff
@@ -140,3 +163,99 @@ func (p *Plugin) getCVRCount(volname string, isCSIVolume bool) int {
...
+		return err
+	}
+
+	p.Log.Infof("Marking restore as completed on CVRs")
+	if err := p.markRestoreAsCompleted(vol); err != nil {
+		p.Log.Errorf("Failed to mark restore as completed : %s", err)
+		return err
+	}
+
+	p.Log.Infof("Waiting for target ip to be set ono all CVRs")
```
Comment (mynktl) [inline pkg/cstor/cvr_operation.go:181]: typo: "ono"

File: pkg/cstor/cstor.go [hunk 3]
```diff
@@ -526,6 +537,12 @@ func (p *Plugin) CreateVolumeFromSnapshot(snapshotID, volumeType, volumeAZ strin
 	}
 
 	if newVol.restoreStatus == v1alpha1.RSTCStorStatusDone {
+		if p.autoSetTargetIP {
+			if err := p.markCVRsAsRestoreCompleted(newVol); err != nil {
+				return newVol.volname, err
```
Comment (mynktl) [inline pkg/cstor/cstor.go:542]: Better to wrap error with message, like "Error setting targetip on CVR, need to set it manually Refer:<README LINK?>".

**Review by mynktl — COMMENTED** [review]
Thanks for the PR @zlymeda! 
PR looks good. I've given few comments. PTAL.

File: pkg/cstor/cstor.go (hunk 1 above)
Comment (zlymeda) [reply pkg/cstor/cstor.go:280]: the value is set like this:
```golang
p.autoSetTargetIP = autoSetTargetIP == "true"
```

so if the value is "true" it will be true, false otherwise.
I did it in this way, because restoreAllIncrementalSnapshots="true" implies autoSetTargetIP="true" and wanted to provide a way to turn it off.

so now if restoreAllIncrementalSnapshots="true" and autoSetTargetIP="false"  the targetip won't be set

File: pkg/cstor/cvr_operation.go (hunk 2 above)
Comment (zlymeda) [reply pkg/cstor/cvr_operation.go]: fixed, thanks :)

File: pkg/cstor/cstor.go (hunk 3 above)
Comment (zlymeda) [reply pkg/cstor/cstor.go]: done, PTAL

**Review by mynktl — APPROVED** [review]

**Review by mittachaitu — APPROVED** [review]
changes are good

**Review by mynktl — APPROVED** [review]
